### ISSUE TITLE
Question about API Server "https://deal-bench.xyz/api"

### ISSUE THREAD

**Issue by Kevin1cc** [yellowbean/AbsBox#1]
Thanks for the great package first!

# Reproducible Example

After import API,
`from absbox import API`

When I ran below code, I came up with an error.
`localAPI = API("https://deal-bench.xyz/api")`
 
# Error
```
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
Input In [26], in <cell line: 1>()
----> 1 localAPI = API("https://deal-bench.xyz/api")

File <string>:5, in __init__(self, url, version)

File ~\AppData\Local\mambaforge\envs\absbox\lib\site-packages\absbox\client.py:25, in API.__post_init__(self)
     22     return
     24 # print(_r)
---> 25 echo = json.loads(_r)
     26 self.server_info = echo
     27 supported_client_versions = echo['version']

File ~\AppData\Local\mambaforge\envs\absbox\lib\json\__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    341     s = s.decode(detect_encoding(s), 'surrogatepass')
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:
    348     cls = JSONDecoder

File ~\AppData\Local\mambaforge\envs\absbox\lib\json\decoder.py:337, in JSONDecoder.decode(self, s, _w)
    332 def decode(self, s, _w=WHITESPACE.match):
    333     """Return the Python representation of ``s`` (a ``str`` instance
    334     containing a JSON document).
    335 
    336     """
--> 337     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338     end = _w(s, end).end()
    339     if end != len(s):

File ~\AppData\Local\mambaforge\envs\absbox\lib\json\decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    353     obj, end = self.scan_once(s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
```

# Analysis
I tried to figure out the cause by running
```
import requests
out = requests.get("https://deal-bench.xyz/api",verify=False)
print(out)
```
I got 
```
<Response [403]>
```

---> I suppose it was because I can not use the given server "https://deal-bench.xyz/api". 
Is there any requirement to use this server? Thanks!

# Installed Versions
<details>
<summary>Details</summary>
<pre>
absbox=0.1.1.5=pypi_0
argon2-cffi=21.3.0=pyhd8ed1ab_0
argon2-cffi-bindings=21.2.0=py310he2412df_2
asttokens=2.0.5=pyhd8ed1ab_0
attrs=22.1.0=pyh71513ae_1
backcall=0.2.0=pyh9f0ad1d_0
backports=1.0=py_2
backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
beautifulsoup4=4.11.1=pyha770c72_0
bleach=5.0.1=pyhd8ed1ab_0
bzip2=1.0.8=h8ffe710_4
ca-certificates=2022.6.15=h5b45459_0
certifi=2022.6.15=pypi_0
cffi=1.15.1=py310hcbf9ad4_0
charset-normalizer=2.1.0=pypi_0
colorama=0.4.5=pyhd8ed1ab_0
debugpy=1.6.0=py310h8a704f9_0
decorator=5.1.1=pyhd8ed1ab_0
defusedxml=0.7.1=pyhd8ed1ab_0
entrypoints=0.4=pyhd8ed1ab_0
executing=0.10.0=pyhd8ed1ab_0
flit-core=3.7.1=pyhd8ed1ab_0
idna=3.3=pypi_0
importlib-metadata=4.11.4=py310h5588dad_0
importlib_resources=5.9.0=pyhd8ed1ab_0
intel-openmp=2022.1.0=h57928b3_3787
ipykernel=6.15.1=pyh025b116_0
ipython=8.4.0=py310h5588dad_0
ipython_genutils=0.2.0=py_1
jedi=0.18.1=pyhd8ed1ab_2
jinja2=3.1.2=pyhd8ed1ab_1
jsonschema=4.9.1=pyhd8ed1ab_0
jupyter_client=7.3.4=pyhd8ed1ab_0
jupyter_core=4.11.1=py310h5588dad_0
jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
libblas=3.9.0=16_win64_mkl
libcblas=3.9.0=16_win64_mkl
libffi=3.4.2=h8ffe710_5
libiconv=1.16=he774522_0
liblapack=3.9.0=16_win64_mkl
libsodium=1.0.18=h8d14728_1
libsqlite=3.39.2=h8ffe710_1
libxml2=2.9.14=hf5bbc77_4
libxslt=1.1.35=h34f844d_0
libzlib=1.2.12=h8ffe710_2
lxml=4.9.1=py310he2412df_0
markupsafe=2.1.1=py310he2412df_1
matplotlib-inline=0.1.3=pyhd8ed1ab_0
mistune=0.8.4=py310he2412df_1005
mkl=2022.1.0=h6a75c08_874
nbclient=0.6.6=pyhd8ed1ab_0
nbconvert=6.5.3=pyhd8ed1ab_0
nbconvert-core=6.5.3=pyhd8ed1ab_0
nbconvert-pandoc=6.5.3=pyhd8ed1ab_0
nbformat=5.4.0=pyhd8ed1ab_0
nest-asyncio=1.5.5=pyhd8ed1ab_0
notebook=6.4.12=pyha770c72_0
numpy=1.23.1=py310h8a5b91a_0
openssl=3.0.5=h8ffe710_1
orjson=3.7.12=pypi_0
packaging=21.3=pyhd8ed1ab_0
pandas=1.4.3=py310hf5e1058_0
pandoc=2.19=h57928b3_0
pandocfilters=1.5.0=pyhd8ed1ab_0
parso=0.8.3=pyhd8ed1ab_0
pickleshare=0.7.5=py_1003
pip=22.2.2=pyhd8ed1ab_0
pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
prometheus_client=0.14.1=pyhd8ed1ab_0
prompt-toolkit=3.0.30=pyha770c72_0
psutil=5.9.1=py310he2412df_0
pure_eval=0.2.2=pyhd8ed1ab_0
pycparser=2.21=pyhd8ed1ab_0
pygments=2.12.0=pyhd8ed1ab_0
pyparsing=3.0.9=pyhd8ed1ab_0
pyrsistent=0.18.1=py310he2412df_1
python=3.10.5=hcf16a7b_0_cpython
python-dateutil=2.8.2=pyhd8ed1ab_0
python-fastjsonschema=2.16.1=pyhd8ed1ab_0
python_abi=3.10=2_cp310
pytz=2022.2=pyhd8ed1ab_0
pywin32=303=py310he2412df_0
pywinpty=2.0.7=py310h00ffb61_0
pyzmq=23.2.1=py310h73ada01_0
requests=2.28.1=pypi_0
send2trash=1.8.0=pyhd8ed1ab_0
setuptools=64.0.3=py310h5588dad_0
six=1.16.0=pyh6c4a22f_0
soupsieve=2.3.2.post1=pyhd8ed1ab_0
sqlite=3.39.2=h8ffe710_1
stack_data=0.4.0=pyhd8ed1ab_0
tbb=2021.5.0=h2d74725_1
terminado=0.15.0=py310h5588dad_0
tinycss2=1.1.1=pyhd8ed1ab_0
tk=8.6.12=h8ffe710_0
tornado=6.2=py310he2412df_0
traitlets=5.3.0=pyhd8ed1ab_0
tzdata=2022b=h191b570_0
ucrt=10.0.20348.0=h57928b3_0
urllib3=1.26.11=pypi_0
vc=14.2=hb210afc_6
vs2015_runtime=14.29.30037=h902a5da_6
wcwidth=0.2.5=pyh9f0ad1d_2
webencodings=0.5.1=py_1
wheel=0.37.1=pyhd8ed1ab_0
winpty=0.4.3=4
xz=5.2.6=h8d14728_0
zeromq=4.3.4=h0e60522_1
zipp=3.8.1=pyhd8ed1ab_0
</pre>
</details>

**Comment by yellowbean** [comment]
I can't reproduce with **absbox=0.1.1.5:**

When settting up the API 

    localAPI = API("https://deal-bench.xyz/api")

, it will send a `GET` to `https://deal-bench.xyz/api/version`, pls make sure you can getting response from 

    requests.get("https://deal-bench.xyz/api/version",verify=False)

otherwise ,it is a networking issue.

**Comment by Kevin1cc** [comment]
Thanks for your prompt comments!
It was networking issue. I finally got the cashflow output successfully. 

Also, I found this is the first Python package for Chinese ABS, which is uneasy and meaningful. I sincerely wish you and this package become better and better : )

**Comment by Kevin1cc** [comment]
Thanks for your prompt comments!
It was networking issue. I finally got the cashflow output successfully. 

Also, I found this is the first Python package for Chinese ABS, which is uneasy and meaningful. I sincerely wish you and this package become better and better : )
