### ISSUE TITLE
Loan Asset Type pool issues

### ISSUE THREAD

**Issue by Orangemaple23** [yellowbean/AbsBox#68]
Hi @yellowbean!

Thank you for adding in Loan asset types into Absbox! 

I've noticed an issue when modelling loan assets in a pool and then when buying the revolving assets. 

The pool flows show that the balance goes negative and then get's increasingly bigger as the model runs through the dates. The collections received aren't indicative of the negative pool balance so I believe it might be a bug, I have attached a jupyter notebook showing the issue. 
[Loan_asset_type_negative_pool.zip](https://github.com/yellowbean/AbsBox/files/15322007/Loan_asset_type_negative_pool.zip)

Thanks in advance!

**Comment by yellowbean** [comment]
I think I can nail the issue, will look into it now

**Comment by yellowbean** [comment]
If you can connect to server with version :  0.27.21, the issue shall be gone.

![Screenshot 2024-05-16 at 03 02 55](https://github.com/yellowbean/AbsBox/assets/1008321/3be0749d-de5c-43b2-ad27-e1ea2f0f741d)

**Comment by Orangemaple23** [comment]
Thank you!
